# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: central_management.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='central_management.proto',
  package='central_management',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18\x63\x65ntral_management.proto\x12\x12\x63\x65ntral_management\",\n\nServerKeys\x12\x11\n\tserver_id\x18\x01 \x01(\t\x12\x0b\n\x03\x61rr\x18\x02 \x03(\x05\"\'\n\rRegisterReply\x12\x16\n\x0enumber_of_keys\x18\x01 \x01(\x05\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\x05\"\x18\n\x06Server\x12\x0e\n\x06server\x18\x01 \x01(\t\"\x0e\n\x0c\x46inishParams\"%\n\x0b\x46inishReply\x12\x16\n\x0enumber_of_keys\x18\x01 \x01(\x05\x32\xf2\x01\n\x11\x43\x65ntralManagement\x12O\n\x08register\x12\x1e.central_management.ServerKeys\x1a!.central_management.RegisterReply\"\x00\x12=\n\x04\x66ind\x12\x17.central_management.Key\x1a\x1a.central_management.Server\"\x00\x12M\n\x06\x66inish\x12 .central_management.FinishParams\x1a\x1f.central_management.FinishReply\"\x00\x62\x06proto3'
)




_SERVERKEYS = _descriptor.Descriptor(
  name='ServerKeys',
  full_name='central_management.ServerKeys',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='server_id', full_name='central_management.ServerKeys.server_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arr', full_name='central_management.ServerKeys.arr', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=92,
)


_REGISTERREPLY = _descriptor.Descriptor(
  name='RegisterReply',
  full_name='central_management.RegisterReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number_of_keys', full_name='central_management.RegisterReply.number_of_keys', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=133,
)


_KEY = _descriptor.Descriptor(
  name='Key',
  full_name='central_management.Key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='central_management.Key.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=153,
)


_SERVER = _descriptor.Descriptor(
  name='Server',
  full_name='central_management.Server',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='server', full_name='central_management.Server.server', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=179,
)


_FINISHPARAMS = _descriptor.Descriptor(
  name='FinishParams',
  full_name='central_management.FinishParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=195,
)


_FINISHREPLY = _descriptor.Descriptor(
  name='FinishReply',
  full_name='central_management.FinishReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number_of_keys', full_name='central_management.FinishReply.number_of_keys', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=234,
)

DESCRIPTOR.message_types_by_name['ServerKeys'] = _SERVERKEYS
DESCRIPTOR.message_types_by_name['RegisterReply'] = _REGISTERREPLY
DESCRIPTOR.message_types_by_name['Key'] = _KEY
DESCRIPTOR.message_types_by_name['Server'] = _SERVER
DESCRIPTOR.message_types_by_name['FinishParams'] = _FINISHPARAMS
DESCRIPTOR.message_types_by_name['FinishReply'] = _FINISHREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServerKeys = _reflection.GeneratedProtocolMessageType('ServerKeys', (_message.Message,), {
  'DESCRIPTOR' : _SERVERKEYS,
  '__module__' : 'central_management_pb2'
  # @@protoc_insertion_point(class_scope:central_management.ServerKeys)
  })
_sym_db.RegisterMessage(ServerKeys)

RegisterReply = _reflection.GeneratedProtocolMessageType('RegisterReply', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREPLY,
  '__module__' : 'central_management_pb2'
  # @@protoc_insertion_point(class_scope:central_management.RegisterReply)
  })
_sym_db.RegisterMessage(RegisterReply)

Key = _reflection.GeneratedProtocolMessageType('Key', (_message.Message,), {
  'DESCRIPTOR' : _KEY,
  '__module__' : 'central_management_pb2'
  # @@protoc_insertion_point(class_scope:central_management.Key)
  })
_sym_db.RegisterMessage(Key)

Server = _reflection.GeneratedProtocolMessageType('Server', (_message.Message,), {
  'DESCRIPTOR' : _SERVER,
  '__module__' : 'central_management_pb2'
  # @@protoc_insertion_point(class_scope:central_management.Server)
  })
_sym_db.RegisterMessage(Server)

FinishParams = _reflection.GeneratedProtocolMessageType('FinishParams', (_message.Message,), {
  'DESCRIPTOR' : _FINISHPARAMS,
  '__module__' : 'central_management_pb2'
  # @@protoc_insertion_point(class_scope:central_management.FinishParams)
  })
_sym_db.RegisterMessage(FinishParams)

FinishReply = _reflection.GeneratedProtocolMessageType('FinishReply', (_message.Message,), {
  'DESCRIPTOR' : _FINISHREPLY,
  '__module__' : 'central_management_pb2'
  # @@protoc_insertion_point(class_scope:central_management.FinishReply)
  })
_sym_db.RegisterMessage(FinishReply)



_CENTRALMANAGEMENT = _descriptor.ServiceDescriptor(
  name='CentralManagement',
  full_name='central_management.CentralManagement',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=237,
  serialized_end=479,
  methods=[
  _descriptor.MethodDescriptor(
    name='register',
    full_name='central_management.CentralManagement.register',
    index=0,
    containing_service=None,
    input_type=_SERVERKEYS,
    output_type=_REGISTERREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='find',
    full_name='central_management.CentralManagement.find',
    index=1,
    containing_service=None,
    input_type=_KEY,
    output_type=_SERVER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='finish',
    full_name='central_management.CentralManagement.finish',
    index=2,
    containing_service=None,
    input_type=_FINISHPARAMS,
    output_type=_FINISHREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CENTRALMANAGEMENT)

DESCRIPTOR.services_by_name['CentralManagement'] = _CENTRALMANAGEMENT

# @@protoc_insertion_point(module_scope)
