# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import central_management_pb2 as central__management__pb2


class CentralManagementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.register = channel.unary_unary(
                '/central_management.CentralManagement/register',
                request_serializer=central__management__pb2.ServerKeys.SerializeToString,
                response_deserializer=central__management__pb2.RegisterReply.FromString,
                )
        self.find = channel.unary_unary(
                '/central_management.CentralManagement/find',
                request_serializer=central__management__pb2.Key.SerializeToString,
                response_deserializer=central__management__pb2.Server.FromString,
                )
        self.finish = channel.unary_unary(
                '/central_management.CentralManagement/finish',
                request_serializer=central__management__pb2.FinishParams.SerializeToString,
                response_deserializer=central__management__pb2.FinishReply.FromString,
                )


class CentralManagementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def find(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def finish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CentralManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'register': grpc.unary_unary_rpc_method_handler(
                    servicer.register,
                    request_deserializer=central__management__pb2.ServerKeys.FromString,
                    response_serializer=central__management__pb2.RegisterReply.SerializeToString,
            ),
            'find': grpc.unary_unary_rpc_method_handler(
                    servicer.find,
                    request_deserializer=central__management__pb2.Key.FromString,
                    response_serializer=central__management__pb2.Server.SerializeToString,
            ),
            'finish': grpc.unary_unary_rpc_method_handler(
                    servicer.finish,
                    request_deserializer=central__management__pb2.FinishParams.FromString,
                    response_serializer=central__management__pb2.FinishReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'central_management.CentralManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CentralManagement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/central_management.CentralManagement/register',
            central__management__pb2.ServerKeys.SerializeToString,
            central__management__pb2.RegisterReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def find(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/central_management.CentralManagement/find',
            central__management__pb2.Key.SerializeToString,
            central__management__pb2.Server.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def finish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/central_management.CentralManagement/finish',
            central__management__pb2.FinishParams.SerializeToString,
            central__management__pb2.FinishReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
